<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Purchase Invoice #{{ $purchase->id }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #333;
            margin: 0;
            padding: 10px;
            font-size: 13px;
            line-height: 1.4;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        h4 {
            margin: 20px 0 10px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 5px;
            font-size: 12px;
            text-align: left;
        }

        th {
            background-color: #eee;
        }

        td.text-right {
            text-align: right;
        }

        .total-row td {
            font-weight: bold;
            background-color: #eee;
        }

        .payment-details {
            margin-top: 20px;
            padding: 10px;
            border: 1px solid #000;
            font-size: 12px;
        }

        .footer {
            text-align: center;
            font-size: 10px;
            margin-top: 30px;
        }
    </style>
</head>

<body>
    <!-- Header -->
    <table cellpadding="0" cellspacing="0" style="margin-bottom:20px;">
        <tr>
            <td width="60%" style="vertical-align: top;">
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <td style="width:120px;">
                            <img src="{{ public_path('assets/img/logo-new.png') }}" alt="Logo" style="width:120px;">
                        </td>
                        <td style="padding-left:10px; font-size:12px; color:#333;">
                            <strong>METRO MARQO (PVT) LTD</strong><br>
                            Colombo, Sri Lanka<br>
                            Email: info@metro.com<br>
                            Phone: +94 77 123 1234
                        </td>
                    </tr>
                </table>
            </td>
            <td width="40%" style="vertical-align: top; text-align:right; font-size:12px;">
                <h2 style="margin:0; font-size:18px;">Purchase #{{ $purchase->id }}</h2>
                Date: {{ \Carbon\Carbon::parse($purchase->purchase_date)->format('Y-m-d') }}<br>
                Supplier: {{ $purchase->supplier->name ?? '-' }}<br>
                Total Paid: Rs. {{ number_format($purchase->paid_amount, 2) }}<br>
                <div style="margin-top:10px;">
                    <img src="data:image/png;base64, {!! $qrCode !!}" width="100" height="100">
                </div>
            </td>
        </tr>
    </table>

    <!-- Products Table -->
    <h4>Products</h4>
    @if ($purchase->bomProducts->count())
        <h4>BOM Components</h4>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Component Name</th>
                    <th>Quantity</th>
                    <th>Cost Price</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($purchase->bomProducts as $index => $bomItem)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $bomItem->bomComponent->name ?? 'Deleted Component' }}</td>
                        <td>{{ $bomItem->qty }}</td>
                        <td class="text-right">Rs. {{ number_format($bomItem->cost_price, 2) }}</td>
                        <td class="text-right">Rs. {{ number_format($bomItem->qty * $bomItem->cost_price, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif


    <!-- Payment Details -->
    <div class="payment-details">
        <strong>Payment Details</strong><br>
        Payment Method: {{ strtoupper($purchase->payment_method) }}<br>
        Status: {{ ucfirst($purchase->payment_status) }}<br>
        Notes: {{ $purchase->notes ?? '-' }}
    </div>

    <div class="footer">
        Generated by METRO MARQO (PVT) LTD &copy; {{ date('Y') }}
    </div>
</body>

</html>
